### ISSUE TITLE
Rquest for the original CAD files

### ISSUE THREAD

**Issue by xuzhiyuan1528** [transic-robot/transic-envs#1]
Thanks for your fantastic work! 

We want to mimic your real-world environment settings. Could you share the original **CAD files** for **each part of** the finray_finger.obj and **the mount part** for the wrist camera so we can directly 3D print each part? 

We have tried to split the part of [finray_finger.obj](https://github.com/transic-robot/transic-envs/blob/main/assets/franka_description/meshes/visual/finray_finger.obj) with blender, but we get a wrong size. 

Thanks a lot for your help!

**Comment by yunfanjiang** [comment]
Thank you for your interest. Please find assets attached.
[transic_finger_and_camera_mount.zip](https://github.com/transic-robot/transic-envs/files/15411793/transic_finger_and_camera_mount.zip)
