### ISSUE TITLE
Instructions how to test/visualize a task

### ISSUE THREAD

**Issue by hai-h-nguyen** [transic-robot/transic-envs#2]
Hi, thanks for a cool work.

Is there any instructions to visualize a task (for existing tasks, e.g., with random actions) and to create a new one?

**Comment by yunfanjiang** [comment]
Thank you for your interest! 
Please refer to [here](https://github.com/transic-robot/transic?tab=readme-ov-file#usage) (the third tip) for how to visualize. To add a new task, feel free to mimic how the code is organized in this [folder](https://github.com/transic-robot/transic-envs/tree/main/transic_envs/envs/tasks) and make sure to subclass `TRANSICEnvOSC` or `TRANSICEnvPCD`.
